language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.4

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - go fmt 
  - go vet
  - golangci-lint run
