language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

script:
  - go fmt 
  - go vet
  - golangci-lint run
